### ISSUE TITLE
remove datasource

### ISSUE THREAD

**Issue by worldwildweb** [Hurence/logisland.historian#145]
## USER STORY
When a user clicks on a trash icon to remove a datasource, this datasource and its associated tags and data should be removed

## ACCEPTANCE CRITERIA

  1.
  1.
  1.

## DEFINITION OF DONE

 - Code builds without warnings (technical task)
 - Code unit tested (technical task)
 - Code is reviewed by a peer colleague
 - Documentation updated (user story)
 - Build pushed to demo server (user story)

**Comment by MiniPlayer** [comment]
Closed because of duplicate with #144
