### ISSUE TITLE
tag list should be updated after a bulk load

### ISSUE THREAD

**Issue by oalam** [Hurence/logisland.historian#78]
## USER STORY
As a user, I want my tags list to be updated if needed after a bulk load so that I can list the full tags (bulk loaded tag should have refresh rate set to 0)

## ACCEPTANCE CRITERIA

  1.
  1.
  1.

## DEFINITION OF DONE

 - Code builds without warnings (technical task)
 - Code unit tested (technical task)
 - Code is reviewed by a peer colleague
 - Documentation updated (user story)
 - Build pushed to demo server (user story)

**Comment by MiniPlayer** [comment]
I think this issue is obsolete.
